todoapp:
  site:
    author: SpringRunner
  data:
    initialize: true

logging:
  level:
    web: debug
    sql: debug
#    '[org.springframework.web]': debug

server:
  servlet:
    encoding:
      charset: utf-8
      force: true
#      mapping:
#        ko: UTF-8